#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf.ceda.ac.uk - 2025/12/12 16:01:37
# Search URL: https://esgf.ceda.ac.uk/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.SImon.siconc.gn.v20190906|esgf.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf.ceda.ac.uk/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.SImon.siconc.gn.v20190906|esgf.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'SHA256' 'cb6d089d2b9a7362b1957f2bf1f11ed7a57b4e0d7dc0fbd80f6b42321dccfb87'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'SHA256' 'cd1e394f5dbcb7a4e7942da81b685cfed8a90bc17f166d8c441790bdcbc68c8c'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'SHA256' '726cc65c750b2bb3903db7a4aec02d8c3ca7aedd15b0edc2c4e0ef081619e776'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'SHA256' 'f7f37116af06265d7348ea364652671419e19370a70743dca6cfc929dffcb478'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'SHA256' '3b5d316308dbce182b297bfc3c8c3bb0f1f3042603f8544c89b0592552ada464'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'SHA256' '335978d0bdb3ac9a264af2f802170e1558232444175af4d72023288ad8400138'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'SHA256' 'aea17096b98ecb2f3e457dee2c79382850797c479c11955ceb545da3e6a5c8a3'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'SHA256' '32e4736fbf5a49b0d36e13dde41555820bd198441bafea97d5a7e43bd8a1c697'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'SHA256' 'b56e063e89be2b0a08e3eb47121b8957fc34792690d9bc3e3cf749ad417adb5d'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'SHA256' 'dd7f67d05e1534f569e8ea4f65b8a5c507ac79f5de144d2f587838257eaf4cb3'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'SHA256' 'd55e1d009a69bbed7602d759d71015109bddc80515b9ada4883ec4d496cf3e33'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'SHA256' '1d7dedf63ad2a423a30bc1e98e1c6a1f844805a98f00a6696ded22805921d3c8'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'SHA256' '117a6c8d2ada05fbf5fa4e12ba9785a499b9633fa41d3be774f2f2cd4914fa81'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'SHA256' 'dfb27c98f7167a4e85cbe36409f3840b84639269cb2883bc13e129c156cba9a5'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'SHA256' '21af4da199321720ac745b9e992a8b4016fbc21be095a261b0fd685b4cafc69e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'SHA256' 'ee6db70dcd4ef1d4f5c3a6aa8691bceb9ecb9f1dd12736eaf48b6e2561d9900e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'SHA256' '07ec183fa2511364b1fb86a3e488ed7d28269fd8fd46917bd5bf0cb7497e001f'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'SHA256' '26ec130c5424b4a57ae33cf78c74600d3eb5ee53a4a540c2dad7940c41e3d85f'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'SHA256' 'bdc89a07820c38cc6c36768ae8dd58f249e188b5aa8151b0f3a7948ad873e32d'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'SHA256' '91287ee44ece22191ff1ede65b6f249117f0f2edf8e29acfcd211630bc9abf34'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'SHA256' '9239afbc4d190e89b08737990bb4d4a51f98490919970520f3d0735b77fb3b06'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'SHA256' '7141724a7358ad0deb898b28ca98938e11691e65f46367c9249f7b3db37f1265'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'SHA256' 'fb0134485663d7c2e47265ac16488564ba52d5cec7f057461c0b864518e26b1d'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'SHA256' 'fb94a5e0a615702e3cc9b61292fb0f5a10c657b8bf0a26da18443c40e65b7889'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'SHA256' 'e89066a3789803fc38c29695e6be11e9a4acf2eaef1043fdf77991f5d5df098c'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'SHA256' 'd4e2c62abf2e201b85bbcb14d38b3e2a59e6e8cf511533568fe7796d6ec37736'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'SHA256' 'c68521321e0c5e93c11c3263407d03fdc7f0d4bb87b3a9d852a47bd38d8c2bb2'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'SHA256' 'a38d4917f1afcd9a95a8a850dbf4f65958e54de0f1edd9f4ce8fef9eac04794e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'SHA256' '5a5ca86dd5a528bf7679db5d076dc91100283a97b14096ce983e958635a0110a'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'SHA256' 'ec380542543fc2028ea70c082a423029446edb5a8a6f2b4902758c502da65034'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'SHA256' 'af7f7aa7c204fa728def8da8e32bd65ca0fb1cbc12eb9dd126663d6d8d0370ab'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'SHA256' '8565133a05b87c23d4fc9ea4357632c934b8288081d6d88651be45345cb128dd'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'SHA256' 'e3f3133752382826c433cbb8a0b400493f307503b5ad9b53c14cf5f0e360abcd'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'SHA256' '3ec9af454103d1ff0804e8164ddc3cc4073751d8411a3da77b3a21841011db5f'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'SHA256' '5756d31783480bccbf841898d4d9419850ad18735346217c8931eddcfae6b5e5'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'SHA256' '72a974d4649e71fcb19f49d8c4a1f6aa52a1b11cc62470bad79a2b83040e8dca'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'SHA256' 'bf3a686d83293c05887ab970962e7fe830b59dc611f893e490718b1dcaa710e5'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'SHA256' 'ebaab4c242c60d57e855f8c9bbe557f27a5dea31b4793ae7d63c67b4074fa9a7'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'SHA256' '1cc3841925adb8b2ead456a0ea60b339233696f36893cdbab406d9a067d65927'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'SHA256' '527b0e17a520e97d945e30e853f5b4b3a2592edbecde5cc20b340914b7ec2361'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'SHA256' '7d1e874347968248a47b7c197add5652cb77e7f3200deb9a74fe5f94d4460a39'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'SHA256' '32d4330fd587b5601ae813d740167b502c604551fe4aa4b00b58b27808be0852'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'SHA256' '42503274f97b89b89565049590c4af4aac187c7916c59d0832192ed56af4265d'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'SHA256' 'cfac8f77030c322335f0dc2f961cfa85df6e2f8a26394991942f9655e9a8c576'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'SHA256' '5aedbf3961f382e3aa1ecc3877755bc3682c7382de8ad7c604d2c4427b9af574'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'SHA256' '75469567ca589ae013b487088b04137cd04463eccd374e782bd4809eb3858f05'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'SHA256' '90b6387bbcbb45deb70895b3aee56343cd2ca478702980b798ed15c3304a8531'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'SHA256' '7397f5e4f0d1420673a994a054b9e436cd3f837c5df0f79c767bf85b4fd73bdd'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'SHA256' '164ffee92d7b957a850df3b65f73016a7219af2bc6f1fceb8576de446da595b3'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'SHA256' '632aec0bc82c6af12c7a9cba9dcaf4ad021558f5b2297ecc84d489ff22f2d929'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'SHA256' '3b7389a2b13f2a14bb94c58f10792c39aa6ac7b2d6656b7e8b31c30d2ec23113'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'SHA256' 'e088b55ef1e3a1ccd9dca56b88274205d6c9b81a0c4719a160f22d321c3e881f'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'SHA256' '73080315a967ebf7760440223a158b0b6a373bc5bcbcadcada6505bf8ef760b7'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'SHA256' '4b3f2bba88d757b679c9fcd45c10b5d2a180c0dae2ac958db1724158848061d0'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'SHA256' 'e7c396cad74311ac0f65d8a213b4b9c7cc504648199f134fadc2a36200b08177'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'SHA256' 'f83bfa2c130226da6eaf888965da7527f31357d9186679dad632688aa4dccfe6'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'SHA256' '9f27118a915f571cb634a20468a115221f9e56075fcd62687368462a8f7bc605'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'SHA256' '0863ce7f43ef0f992321208d524eb4d4e374e61a4baa2d39105927a33058f8ee'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'SHA256' 'ca75637413bd0a53ecf04483368f001cec975a9c76d36af908cb7e79b0b7763c'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'SHA256' 'a3f66f8be4dbb2090e22dedd9ddbab37d86e9b8b01991468dcd71233b206da67'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'SHA256' '0da4ad1bb36489a527e211faa42259b5267ac03a4dcea6d33a54c40b1cb9edff'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'SHA256' '94fd69b26607317b254e193d410db4b1a285579360c119e43aa6e30577700576'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'SHA256' 'f49b19b10e8e71be8659313855a61d67feb94d154abc849d9be88253c8f6ecd3'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'SHA256' '9e97ef3cca2e2c8d8536aceb8430ae6b681c755777438e85b7fa015e84e18472'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'SHA256' 'ef49492f4f06b88e55fc8da0780202188b80d76dc2552dc13bf999da461c59be'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'SHA256' '0c29b07a57dd1c1af1a29a5c5ee5103066750bc0dcf3abcb62359cdb29f1b0d1'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'SHA256' '9f0a8405cf7d4fb80b34eae466297f245740cff7c88f078a1bb9ab32e565e109'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'SHA256' '8e08a8a1f9bd38a02c65b3d6d7706edff419a389d9c92724d60a55a1356bf870'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'SHA256' '822a4359b960cb5757f0a680aa58ecffd549073d399cde46183b7e104c1f7db8'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'SHA256' '469c6e387343d8e506ce5d3f4fe3f8cff6b6eb978dca2ad95f5d001ba70c4bb6'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'SHA256' 'bb654c6635688220261952605c16b26c3446da53c173d3bdfe2e0d8a696b76b9'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'SHA256' '8569b9ff8ac7ac375a81e459550d94feb29a5e7a057f6dcea5b025c909474060'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'SHA256' '307c44e8fef286c3def16a7405fdb69b52795867d482c5d777181f848728fa2f'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'SHA256' '664a0d1d2f49cbc7e6f7dda94ce739130a070cd634c4012680538d5e19f004f1'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'SHA256' '6a4489df9975da92e3ca693cde841031cbba534cf265b9cdbd1da2c788c4b17a'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'SHA256' 'a4b06af943c7d47d1ac5cc95d46fec7b2876a97282dc3682b4a136f74c597c5a'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'SHA256' '5678943114076ee5bbe8254193f029d5a03475836eec79ccf653f8b495494a3c'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'SHA256' '00ee41ffff066f6b8da21d443da5fd8044dfe2a209dc5822d853a0070cc6a083'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'SHA256' 'a5087c40e5609ca0f19a6d390418d8fd786675b1dfbb72343e1f1f798e3e70e3'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'SHA256' '4118e82982b27e1b7f4acae86245c9bcc9acf93aeaac94a5a4dc25c568df615e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'SHA256' '04a46fb02d4684820f6ba390bfcf0254b1907ed0c5195c45c1ab1a98535ed6d3'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'SHA256' '438b5d388e104a04a625062d8ef767d27ba545e462cebb7480d96140ff834ef5'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'SHA256' '31e4cf2c963e3d328221460ff98669d73538ef9a39eed69dde19964556e21e99'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'SHA256' '05cfd6a07c32bc957eaa04edb8a6a524b1085bf68b3e8b473141db6e5ea7fe69'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'SHA256' '19c99201a50a32a5d0784e0fafd0fad8dacfa34475334acecae2728ac533df2a'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'SHA256' '80f00761dff4b6d8482b58f9823094b72e63ce6c80dd13dd03fa1099958d4fd1'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'SHA256' 'c16b6e3d9a50170000c5c378e515e98db98045035829a6e7eced45836793492d'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'SHA256' '529ffef51ea565365bee2498d16dd3211fee374a6e5356724909e6abddc10143'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'SHA256' '17148248053c9cc47420ecb38817aeb66ed0d5ec089b325a9b3bfb4d23f2072a'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'SHA256' 'f8652d2fc38b20159f8d7b6bb127e4254752edf3f117fa453944214ca227bcd8'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'SHA256' '3c6433a29e3e43145e3b7a8224998e17b9bb68fd66282e313dcf0c642780db0e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'SHA256' 'e1ec48a8a400b90828a19bce242646bd26002277e5f2a0e2ed71f5f9f119e94a'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'SHA256' 'f5ccfbf9cccd302c4c1e7d4e68cba71a4007f46bbca248b0794a8239f3e1725e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'SHA256' '6a1fcd6db52209640a34b9ae910e736d5a16b92f37a5b5a51a34e18c8cbefb8e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'SHA256' '8dbb47afac88c232481544c59d3e9388d7bf7f2bf26d9cc057bed1ced354227e'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'SHA256' '0dff6194547e90ca8f15215b75bcf4ce5587d06319d702582e98cdf4c956a8ae'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'SHA256' '3b151670842d5127810215e95dfadea4e0328e74426771e25019aee21bd9183b'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'SHA256' 'f678339f68f6a7dee6963e2bb3aad81d203340b2aa80f48992cc13e495cd72ea'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'SHA256' '094d0f025ddb1c439c4e77fa40d2ff2f53e14929df2e48068d13a389a8ce1bbd'
'siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/SImon/siconc/gn/v20190906/siconc_SImon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'SHA256' '5fb379fc5277871537b3c205280aa1a4ef888afcd69478a0e4e6314d77c31ecf'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 100 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
