#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf.ceda.ac.uk - 2025/12/12 16:00:49
# Search URL: https://esgf.ceda.ac.uk/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.Omon.thetao.gn.v20190906|esgf.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf.ceda.ac.uk/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.Omon.thetao.gn.v20190906|esgf.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'SHA256' 'a3a533c98c7d962b7fc5bef6867db5388c24dd69309a4d4d31d02a8a529d8ccc'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'SHA256' '6c60725e752edea24178819c05bf62371c9724190c3978be9341c0195bb8f753'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'SHA256' 'ae9d5ecd71e37d167003e9b22aa4c01d597260ec3a394b0917199ffbafa5c38e'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'SHA256' '36aaeafefc02e8ea1207b260871a8a6aa2da6f3e72cd277f8f719f28c948f9ee'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'SHA256' '0c044c417fe4089d19fc08626d9632a335bebf5b87b6473e0dadae7a596d8e9c'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'SHA256' '300efe44e545e026575e774605888ad68d58da4adca9e350af8b239724703fa6'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'SHA256' '71eafb39b3fea054bf3ce6fe8bedcb808b1fb593876125aa1e4d659b4bda4f69'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'SHA256' '656461b36b3bbdd5efc45616cd41ba1a6302974cc1aa17f52f9ebfa8fba40c21'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'SHA256' '746950b08b27c4f5c9888b41f4a7d83cc755f5d96a83a87aa34ae585e11c70c4'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'SHA256' '74e245d403719ca55fe00a31b75a148405509517526f57e8c792659008e7d747'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'SHA256' '210dd83d2014bf644b05e687a821d02ef30eeba56a5317d8e88b0d062a7a7a83'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'SHA256' '8c4bc07d020d6739a6b82d065cf8cbaf1af25d4159855a0d4ea874f8cf1d30db'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'SHA256' 'ca7775788c703d0bb4ade9ade395be257737c6929d14db00ab76ed0ce7b2d767'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'SHA256' '77a5298aae1108d31187e19f128522690fcd42e5baf5228087e6d314ed6913fe'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'SHA256' 'f6bab6d099590932941d8441ade1a7afee488fd41b4ba86a9708e02fb29f8b25'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'SHA256' '47e7f06348f7965527d4f107537b3a6c3755990b612b9206fbfbd572dee5227b'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'SHA256' '4d5053d6c5ad125abd49cae269686efac2dae481477ccdf4d31547ceb65afdd8'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'SHA256' 'd3701e7b98b61b8e32bc921d952660188c31edf625e8e7518af4985812a49483'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'SHA256' 'ded1e836ab49d251b126529b9bc5c36af82c491a3f18c18dcf9466fc6891637b'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'SHA256' '7384c7f904abc3a64dade518ffaedcb7c98e929720d5934403f0661a935b77cd'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'SHA256' '81e380f5fe7239a5765f269d6878a6fb80461b848a63bd688f3ff109e32f725d'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'SHA256' 'ef82c1b348be485e51315003790e5a715285752bb1fa3e9bbbb8d018477ea328'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'SHA256' '98feddd6985d53a7649ccc876663bec67834a5d58beb79e3f75c1fa798b1b7d5'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'SHA256' '1902a8587f22bb9d1c900b33c9235e64deb6c9be25b19f28946139d104f08d1a'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'SHA256' '5bcbf5d7ccc2668cd6bf368d5db95c783864714ca6399b70dfe7e41ca1e7cc7a'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'SHA256' '07df6bb5fd8939dfccf4798e9a4f5e5190ceb431fe26726db2aeb6943748fdac'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'SHA256' '395b9fd307d04c8ed6741a56ac9afb2ccee48c0210dc9172905acd2901ee1c3a'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'SHA256' 'cbb0191542a91b28e0f6e3c55af041fb23a2f9649e36b1e3b8cc603c4b8b3a49'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'SHA256' '8582bd6f031ba0fb97a2fa45c65cdd7d06b10ac3cfbfe4e809c669775f618f72'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'SHA256' '3c5556073569d92c9b3615a06a106aeb2c791149dd7046bc512ef67f2d733ef5'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'SHA256' '7ab848ec5f4ca83adb5bc74980fad3fe3107ffc19309feb0424fc370482f6ea8'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'SHA256' 'e3a6de77941a1433c8fb577b44a2ac0eb55b7e58adad18990a3af75e77a7a888'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'SHA256' '0f39254a00996cd03e9c8d57b0d3519781c8cfed4fbed04c88c497c80570a250'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'SHA256' 'c910c45dae55212d513034a3ff6f3cfe65b7fa7c5f0067c46294d4d470912630'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'SHA256' '2dd8145936fca5aabe755aa48c3749f7d17429b9f6b0038c48b26b42c134734d'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'SHA256' '77f91ee6699fc0d5f4bae4fe4ad53c546ac43343039f22f7e708da6af469d868'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'SHA256' 'c37a8e6f994abab8ff51f52ec485ca5f74d015d52fbcab6656252ae6c443d1b8'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'SHA256' '4896e5e6d5646dfe721016a1086a8cdebb7e246f82d0f60ca0d20ddbc99b1bff'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'SHA256' 'ca25017b5e282c9630a3ad05ed24f685573aaf22bbb6a26cd780cd4e392f5366'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'SHA256' 'fbc9dc130a5d043bdcba07d571db398826b48bad9c129a592bbe3492b3f8623c'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'SHA256' '357751f02f00d956cc88cb3157b1c2bcd9ac780adb7399076dd9d258219a3228'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'SHA256' 'eedb4bea1d991e46095b1f9edf4ab11a547263c82bf159e7fbb600c7d82e0351'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'SHA256' '074f3e1bee83d5ad93a6b104a16c80d14a7aa8b5928de10685e079de0635f50d'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'SHA256' '451ff6192a2d4fa90358e03d4a95c32b3d4a623ece7c5606a976472d428b911e'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'SHA256' '24cfaf99b90deda0ca8f6b11005ba70f0c4f964ff5ad4f2200c407ee5233d1eb'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'SHA256' 'b369640c91361ec222ca84d81416389b92679e95c470e4099d0e9f158392e79d'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'SHA256' '29141b1d053a39b9d5921a5ed679866afe82e4764494752ac48b86110e3d19ff'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'SHA256' '4d716f2071ea958aaf4158059a215c42cf9bd5bf6df0802d84ec7340ea0378c7'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'SHA256' '7d9a25e2b669608d199d7214b20e7452382bb5402676769642e45f93a9ed0d80'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'SHA256' '5723ad35030bb100d6d35d1dd43972d528b6672cf091b777977949f6bf8e2ceb'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'SHA256' '12ba045f495cdab9edb8bf57cd95f05fdb69a7191abb99b49819d119d1005698'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'SHA256' 'fb84501dc3bc2def8ba991681418104c83c19cf9ca056426d5a2c0f902de4df5'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'SHA256' 'eaf02e21f1f312c0250c69ae86d45df983c50e9c3e6c71209e1952cf458005b6'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'SHA256' 'cb31130cd1007265ba477ceba99c0ac61faf4b183722111c661ea27a546f4029'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'SHA256' '1e4d8f05143e903dcdbb64d535c0cc3330f4a636597200f60a5e0f67e65f3476'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'SHA256' 'ef5b73777dded5215003db6671b00043e63f9c20bbf0695c5c4f489d73d450db'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'SHA256' 'e5bd0177dac6e7d30b05ed994377aa2153bca3b01d8c319cf5c77f97013c319d'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'SHA256' '08964ea02ff16c0585680c04792aef9cb21b28493f81587c0f6526c01bfe6661'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'SHA256' 'e48ed2515ee981276e943d0c7357eb17885f73f9587430854bd54fcfb4874386'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'SHA256' '5d2c77a1304bba870c18291c39f03b762088c51bc1b4d732209c7428ea1742c3'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'SHA256' '997c16fa4c7a8ef566518cc7b8bbc8d99677fb98f388ae926a08fc45a35393be'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'SHA256' '338c56258ef79fb53a23cf295dc5d3bbd5557802565913583b6f34de0704e16d'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'SHA256' '74c273a0e7826f3bcd57213c1d1e7fa22f10367d5bb54882ccdd23612aab5a14'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'SHA256' 'bd65db1b319b7a998d586176ed77947ee2c78f6fdfce970c1966c89b057cf816'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'SHA256' 'a2a16de8bf3eb2c91aec981c37db87696fda890ea282dbf4c8f30dfb179939c2'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'SHA256' 'a0b170d79fa8b46bc0297f971417dfe2e76255602012f2c1e575a7ea9bced73e'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'SHA256' 'f274f56c103d40055a95d41ff2d832fd23a927cf73105003e428eedb5d663ed5'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'SHA256' 'c5f14f2b710d3f467c3dc3b3c6fd99233464cadd0961647d4fa737b8460171ed'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'SHA256' 'e8cd7c5ced2c719612c428b38b2f36a54008eb6a724df31931d94711c568e3a4'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'SHA256' '8494991551883751744a389d7bf2cb98d2dee03883805767b6ab47c03b15c29d'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'SHA256' '7467dfd107f3741bbd74c75c2cd12704358e47aa532a258cb5ff459aecc7614a'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'SHA256' 'ed2523d244b886a1674cb6a083625cee7e32db8e6767d411779d33a63c00d899'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'SHA256' '6d429cc9caa89625244e2daee807f2ec3067814eb13932de42c7ec62864effd2'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'SHA256' '9f5637ee13d08ed2ba0b264f68fdd83c979bcba2b7bb1c6f4b33c7949907dd5a'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'SHA256' 'ccda3bbae187a57621b5708e2db69257f4daa9676b156b0f3ee9df2cddcee056'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'SHA256' '8365e7bc563cfa986adef06238ae3a3da501efbf320540ca515d02a0faaf19b3'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'SHA256' '257de13fcb7e470f9af4e671e518a74fa095f5020d780ac94adee4dad7f28247'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'SHA256' '1b34bb8f6b3d612f7d9b805c1aa8362b7bed81ef640767930b6f3d40c82b8990'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'SHA256' '70ed0dd1186eb5f5a57cdd152ff31fc01b29327d95071d472a90c737d1d3fb0b'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'SHA256' '772effef910a1007253c70454aee4c79b0b8ddf34e3d77b9467c5947a1563cdb'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'SHA256' 'b2eeee908d20d7df78787f6142383547cc6160a748bd424a2bc3d578c27e2176'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'SHA256' '14982f29c28c42fa664b66abd8ab19a12a3ca9c6af5bf27bbe3259b195a894ee'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'SHA256' '06e5b5d7b74ba3c57bbbf9610e826d90cee908b0d60e013c3bd5f5315a8018fd'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'SHA256' '7f494f14817ece26adf2cc0188d76832ce1a1b7280904956838fa0f8268bd488'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'SHA256' '617e525c56600f63fdbf714737a1032f90463ffa84963b1da5b365fd0c6de023'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'SHA256' 'a2e767f33fa8cdf72aeb3c1f2b41f9a9e2686524bf23654715d7d4d69728f5ef'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'SHA256' '830517b22f0f9e65959e70eb37f2c753a5a44fc4b7c144862fd8ae601da56559'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'SHA256' 'ef686622c80e2a09a5fc2a8d242998324f59a9c4a573e29a3e0aede7aa9bacb7'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'SHA256' '94e43c0ff9883d242f28b9c9a5dac20d9e6554b5601ea7dca94dc5e2677f0285'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'SHA256' 'f78b8d84a9e339fecaf7ebca250ced60c1141ed96627fcc03b9b31412d036f11'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'SHA256' '846091fd4b6463776d095b7d7f6d64afb7f057bfc03cfde931ac354e2d22895f'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'SHA256' '456d2a3f2a28622edaa619d243102a32f86d5313e68d227acf4e6e9ebc65de8b'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'SHA256' '9052a3bd6910d680deca923eb4d4b5e6aa46bb428122e08c3aebd80825fd5983'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'SHA256' '0dcf79f4ca50dd742b81419352e496f93fa2cf0eb208864251b76a8f6270e5ec'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'SHA256' 'c7b77f824a9cf690541e4ca22e22a9356ef80689c4bd442e376db8c271c451fc'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'SHA256' 'f8b7e5dea79e3e688367432158b50f4438c8c5482490f4b2b644ab1d2be1694b'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'SHA256' '5b35661bcdd5f62bbf32865d94b7b39117885d9ef3b565cfaa38584349cd45dd'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'SHA256' 'c5daad4fe92406660104da90ff4b72ee4bf4e7b984937fb1f5fc888c272c1023'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'SHA256' '9a999b03d99177fc4155a66070e386ec37cbba6180ed3691f60947d89d5412ae'
'thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/thetao/gn/v20190906/thetao_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'SHA256' '328fcfcd0c95dbf93fd001e73ab3da9286a76e995ec6a282983a99eb1efbe875'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 100 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
