#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf.ceda.ac.uk - 2025/12/12 16:01:10
# Search URL: https://esgf.ceda.ac.uk/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.Omon.tos.gn.v20190906|esgf.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf.ceda.ac.uk/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.Omon.tos.gn.v20190906|esgf.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'SHA256' '190d8b6e9aef89bf1c4f88327db0ee4129febcf25cf611cc8f700ce3e0798f5d'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'SHA256' 'a72d9184f5687bf2d33afbc5fecb6e26612c455a57e60006c2e18aa709896f6e'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'SHA256' '99ba06065ba553044153b271565f23271a931763be98b7d1d45456cc3e56e4d0'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'SHA256' '876fc894370a32ec28f3d2bd4dc6c24f8547e6de9a437536ccbee6e4f2d098bc'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'SHA256' 'fbd313779db3560f5b7dde0e4a039d7444812d555ee31bbfec8d73d4dad16472'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'SHA256' '0661c20ef09db8d4a4b91ebb67236511eacff4ff949abc37023d3cc6adfed7da'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'SHA256' '7190776a90dbbd8af778f83acbddce4f0b11a3243ea8a541686fb4ca92cb13c8'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'SHA256' '42af88b95b9dc5e1727bff9487f6cc9d0562f2cdda8699d69364833100cf5e4e'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'SHA256' 'a839df2cae4915a669a6cdbc7207d089e6778f623998c1198278b98bb80edc4a'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'SHA256' '32d830da8841329aeb92602a63b03700d1275cdb787d8edd5abaf0c771d349da'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'SHA256' '6f06ce94c7acb9983cc56fea456fdd756c009ea399a9778a89419c64b64ce2ec'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'SHA256' 'c370cacc5ab5ad1acbc4838d78f5fb86fcb03023730bd8da9398b5f85fd4b592'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'SHA256' '38e0ed202329805d518cf621b1d9239c085928094d74d8bc456ad2dfafc61418'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'SHA256' '80343fa92542194f902bff2ad2faff1eac101dec6595cd078cf519dfe9caf2cd'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'SHA256' 'd044fed26bf7264c8b2ed2292d26e72c30cfbae5bc0668b069ca8717e0190b16'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'SHA256' '80d505903814f4ac1c955ed37e921190ce16a78b966a36d75ee6ade708bfafc4'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'SHA256' '2a398ca8ff28e9cc5e669410056af0f187ae8d50ae10d1a3eab090daef4593e8'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'SHA256' '35a04be5af68cac818e149ae56652de3c13e65bc2755f69d5e43d86ad78f6f8a'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'SHA256' '7224f976c63f9dd7d98ec3bf3c2fa9245bb691eb9092823ac0f279e13bafc38b'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'SHA256' 'd6d9a0f95e6bfbf47a554a0c4e64f0884c9669c3975d942207fb03fa8879191c'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'SHA256' '2b8f18208ae1fb56bd5e19b91d799ba459bbb432bd1524b9a288d1ad092c3a91'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'SHA256' 'd98223bb36a2d248cc5a320ba866c01cb3cd7c0cb9ef859eecf603af6bb7636e'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'SHA256' 'ff2c43eb5c0da1e5ef0794ff54eb95aa6bcc4bae1e42b088dfc055bc19260205'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'SHA256' '3a4230b94b6d30ead6cac3267e1fce99424a1f9553339138be72d1c4577811d9'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'SHA256' '6dcf4856fd1b4c07bf40b0f931ab8d784140a81e654d52c5f030d7004bcb598c'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'SHA256' '02601f736d75a4391965a2638fa6d6d5ffeee921be05279cc53b28645ad90d60'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'SHA256' 'b3d24a23292b31b296aeb496f9a52bb0491e86899fb4104e0ca1a8042d19f3f9'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'SHA256' 'ad526a8dd3c8934aa44437dac18d919b4927caa4e31f72763b4cdd8fe8fa5836'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'SHA256' 'b2255689189e64d12f4f239e3382b3800bb8eb2d160d2117a6938c3715d4c12d'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'SHA256' '41949dd210d2daf54fbf00d07cfaddcd4a91981553182c9faf679e09f0c91332'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'SHA256' '81f27ebb9f74a7129cdf6042cd84f5f5a1892e0e2d25a17068bf28f95803c3e9'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'SHA256' 'a8d7a08083ab58fe220cdfa9451c0d7f1d6334fb28fecbea9a65c1728214da96'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'SHA256' 'b2d4994fd07db949fce9735f896a22cc4a3a88566712abb96bd0314f2295000c'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'SHA256' 'b9e262d4c6dd723d8b4c3afac4cf1ab68a46bb2ecb763b331f8f74459ac91f2b'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'SHA256' '976ff522f46bc13041457648e8f9fad853925aabbf0bc8fe97b6a54858c1e314'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'SHA256' '41acc82651cefa9b70f86a59d901ef2369a95c6473d352c00403a78fcbbbea61'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'SHA256' '3829afea72884f75334afc2d31f4cd6a49734ff4ea908cc14449993a87780c42'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'SHA256' '82f96e7ec1a9638357773e2588d68f195bfca7eae66c7d08f7328fa42e0ba57e'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'SHA256' 'ace00aa55c5e6c1fea0eeafb052cb3f99ddefaa115dcb8b09db1c8b2923b934d'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'SHA256' '847d6cdccbec4570c054b3ac7e8fe7c0517d28aee33cec2cacf48efa06cb457f'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'SHA256' '37aa55565dd74d64b6046bdece188bbfbb5cc5244a80c1867cf74d71d7769fd4'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'SHA256' '15a545961317e293a6e3a48c32eaea73a90ab84748f8b1bbd8df27ae5d87ddb3'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'SHA256' '4054eaceee936597c1d9c56cefc571e9a305354850813c40ad571923ddec01fc'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'SHA256' '40f29ad7dec655c2cbd71c0c230ad303f83bc27ab7a2e3ee23f16de58969d4d7'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'SHA256' 'd59e3853a3436e6abfd7288a1533f2949cd17c4b49b9df2b296deac477c1ab57'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'SHA256' 'dfa7c7ce191d13b50a51fe93f7a54314d4283e6280b1111c1453500863b0b127'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'SHA256' '7ea6531adf7fbc3eac709d64ce1af344420bee5801009e3ed7414de2aaf43edb'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'SHA256' '3a82f31e6e75d5180e81d23db6d8974652c75d84da0cbdede20373b4523fcbb9'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'SHA256' '27e4e246fd8f57655472c54fa725b0391bc80d9396029594a53221aaea208d44'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'SHA256' 'c9f0bcdb6cac3add5f7c9c4de394b008e0cb474d2d8718252276d9416bd97d0c'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'SHA256' 'd72847562983554b5f04b76a5f7d99461aee33c52d695c3cb1b0105429389294'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'SHA256' '141098080c9533ccf1a0debbc3a58716511deba03509f862a3f592880430a5e0'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'SHA256' 'dff6ff1dc44ad2efccdf0ec2bd4111af05e6ee2f337b945bafe4e33efa6760db'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'SHA256' 'b9bdafecc23567da0479e827fb00e668c9734d3b28c54a87225913035b217304'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'SHA256' '840e92a07e534bf99fd1743ee76b8797f489c64e6342769383c7e335861674c3'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'SHA256' 'ee0d33b7feb34254bd606efef83fc08634b5890f7ae62f41e6020611465f4315'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'SHA256' '63e98757036ef3a32f849a790daa4bda969c42f162a8c3862b3c3cc8560a1660'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'SHA256' 'e91e3d9229ce2f77f79e5644d0c5cac895e3efb75312e8c909539a39f5b836d8'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'SHA256' 'ec9d29e8030b044c608256bdeb899faa005f061870001e2cbfb7227a496d89d3'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'SHA256' 'f280da6434576ce006d284541afaf7882bfa12a3be2cc4143d3518d087e709d4'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'SHA256' 'ba26d6ee2b6a4a4be634211008b1d304ee61e5ec8333750b025cf3bf79f75f3b'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'SHA256' '6dc223489f97c5060956d3b5eecef3b3596c0946f4cdd922caf339e8cffc09a2'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'SHA256' 'edb61939560876576bea05d8c1380ad955fee5b238bdd64f3695f17165e0bf5d'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'SHA256' '21d3b29413242d70f53699d632a5e0d781d1df800fbb713606d5573d30664ca3'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'SHA256' '53fcc8712034a45f7cd62fe3a10bb4878e22ac4c6276050520d0ceabaf9895ca'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'SHA256' '2a1bc01661f5d229032a0d71a115abfab92a9e920e5874bc40dfb317411d4946'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'SHA256' 'bb10c141523b31df95a0dea2d29be08a83276d26baad640a55330b288163e161'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'SHA256' '95c99a06ff5b7fde2cfee8c4defd8ed462c204eb1b1033d2ef00456dfffd9a4e'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'SHA256' '7aff98a4d226d6a3ca1f111328c22acf2b048193c6cf6a3b87008a0c0ffe30bd'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'SHA256' '1530a3a8697c86c931836242f7b4b22279f4bd38a3db5d9c0dfca56ede704fd1'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'SHA256' '522a6e0cbd7322d91b6d31c8082e55852a73391d59009a109345287e8a4763e2'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'SHA256' 'aea3669a48ba7052b042fe870c4156dde7f4fba6372ae514855a5c6c339e7ec7'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'SHA256' 'ac393046a4db7c8452e35890199ad68ec70ce477311239e4d6b3ee66275e3e00'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'SHA256' '4af8006ad6992807e6b803d4c3e617dffe4ec7c65dbda78ae711c539d64c4d1a'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'SHA256' 'f9cc4c99071924235a91acf4f6f72d99fc239ccf9391808b0d896c0ceef3eb5c'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'SHA256' 'c05f0bbe5ea2285abadce9f0c35c0307e00afcbe246a4d26d59030f10a9239c4'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'SHA256' '902bae1000b516239975f3ca1865422e5f576a990a8c778088a4baefd6198901'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'SHA256' 'd45831983a37183999622ec24ab6e35f63faf668a040e946efecee5b51eae0a4'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'SHA256' '2912913e7e5af64d7e7a0b17bed839f0bc58722c88f85d5981a215e75a3d8c4c'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'SHA256' 'e70d71e668886b166c446a241ef548b90bc57f311657ed7245275663b7f5fcbf'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'SHA256' 'eb150ca97873609a1d16d24b678f5c183dddcec56a773f5ee4ebc492c8c13a9f'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'SHA256' '2c8d5a5d5de78798efa926ddfd99ff18747aacd6597a2e0878ca08aaa8d93194'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'SHA256' '17d1a6a490df349cde91113b234a8b5b5dad95be98c6878bfad021b88feb70b8'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'SHA256' '47ebe3caebdf568e388b227d43bf6e335e5d51e72f37b902aad76d914972afcd'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'SHA256' 'd116acb84c1d3608ece582b3395a5194767c14a663106cd22dfa2df9e5c5382b'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'SHA256' 'c1d70dc07405d119c0bdac93d74afa5e9e58e38cc1b9a1e2c737523818467d09'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'SHA256' 'e41a946d0d5fa2702c903f2c4e320d3658749cb1af6cd562aec497474bccd73c'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'SHA256' 'e1e9e16ede1d858724c940ae5122767ad9d5c6d699500f224ae8a54824715c2e'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'SHA256' 'a16716ba6a623b97e52f83c9d09c282c868d7e506225f554f002da9e4e0ecd8e'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'SHA256' 'ee045525ff57c2cb340f89def6483bd09d442e71789be2777d033dc82e621303'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'SHA256' 'bbccb2e07e6a6de9b924a371bbe42f99bc3344b7a8859d96fcd9047afb945ca2'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'SHA256' '57335850d0112c5154c1af6548be299cfba849a232fb23de158f0b10642ead9f'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'SHA256' '3f053509a4dacc3e98841a4ef63138ef5633d842cc8f97889929ef997a4a8299'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'SHA256' '5a6871dfc8625142167284d6516140a26c1951d8f4b4d63f8b894c113dd5e2d8'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'SHA256' '2b0dca80295b9eaffae2e6b80d19aaecdfcfb32a9d30bcd66feb670249068e6f'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'SHA256' '92f1c637fe5b245b783b423baaced6036033a02f7a8bf111d0833a8305dd4de0'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'SHA256' '7f976e7a4d27ba4bea922c85f4cd29924e682c3601f9f2ad78102c065e6dc012'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'SHA256' '5bf31cd555dd5e3d8955372d6bf11ae7992b4f268787320f87465adc8a7b01c8'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'SHA256' '1f1b301f03a293a102e936472fbda94923211ad83dc7b9bcaef15008db1ddba2'
'tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/tos/gn/v20190906/tos_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'SHA256' '604aafde4b2a056c06fa3490f67e3984f58a1a1af7a055ebffb593c63acef447'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 100 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
