#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-data.dkrz.de - 2026/01/13 15:53:02
# Search URL: https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.Omon.vo.gn.v20190906|esgf.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.control-1950.r1i1p2f1.Omon.vo.gn.v20190906|esgf.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195001-195012.nc' 'SHA256' '569562e7afa9826d72b8b906edde49472f60ea2af5bf6033a6dc23f834bc3150'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195101-195112.nc' 'SHA256' 'bd1049da9b884a8f36d1cc133295b0c8401cba561096b0b04c293219a27b466c'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195201-195212.nc' 'SHA256' 'b9a70ab306243807fba3cf3580347aa869846e8080fcf7c60c9c04619ec98d08'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195301-195312.nc' 'SHA256' '7950ea5f1c463c2a160a79c89f95a3d4865d0eb49ce7e16ce05d13fc7a71bc84'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195401-195412.nc' 'SHA256' '38dac0f34c858c53ca9f619f5e10fa56c38a1f3d86d0b048933f2ba6460b8fbe'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195501-195512.nc' 'SHA256' '699ddf7cd3f436a609a839b6da554a4dbc0d0080ab38622f8959f084fc6ff636'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195601-195612.nc' 'SHA256' '21fbde9c2a5fdd44b4e749a81fc2595daa1814d363f5c95c662f04dda065b258'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195701-195712.nc' 'SHA256' '815b2a99bbdcee6b194ad51fc386111ef5cd8132b2c94ff6178bdc32a3c08796'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195801-195812.nc' 'SHA256' '2f1f8b731c32eafce019acd67497c2eeabf9560e36c3e2f67f6901ed623f82e6'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_195901-195912.nc' 'SHA256' '8772ba0200a1d677d2e04727bef46f2aa49f0aba33921a3fefc7190780e4c07e'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196001-196012.nc' 'SHA256' '81ea922e215667fd1be2459dd9842836400017f8a1af3ac50fcf0c4fa3221ed6'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196101-196112.nc' 'SHA256' '6cd1167b7ed4500bdfb0805ffdfd53a6813e7ae2ba31e49108d66859ba278196'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196201-196212.nc' 'SHA256' '5cec16d1dbd3488a98cd10d237703d8c230de99f5a72fba4fd6c8d9c6156dd40'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196301-196312.nc' 'SHA256' 'ea63e8948cea1b7b392e98827a3de622c4c394b84b81796d6754f7bf56add445'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196401-196412.nc' 'SHA256' '24c354666ff88d10e27d6c4e352b504f5dc9855fe5b0a783a4b2381314853fef'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196501-196512.nc' 'SHA256' 'e6e02dad0878a7cc45d6412e1acf11bb4617126762dc3d07448e94357cdec0a0'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196601-196612.nc' 'SHA256' 'f59de7c9dff54d5da5cbecf7c72e39adf90541a24855b6c179315fbe1b689fad'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196701-196712.nc' 'SHA256' '7a279a768ded1962bab79c05a63135a4f3b6c2aff0b515ecae1f155f5f0f9f7a'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196801-196812.nc' 'SHA256' 'c97911a74eb285d974ce0818d95f300a7640c6203fd66798aff959c0606ee154'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_196901-196912.nc' 'SHA256' 'e21b99cd88625ce5d662cc8e04880dcf1df40d3bf6b2b4cba99463bad6c644d3'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197001-197012.nc' 'SHA256' '900d2e4e8b2c3332daeacae766c1c957a732018233017f46e730261f814bf417'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197101-197112.nc' 'SHA256' 'dc3687abc63d66f63ea6c57a1c54156de0a3f218c61982b84ee5540457a81c6a'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197201-197212.nc' 'SHA256' '64872b32ddad09539e41a2146dad2a5a95be6a69e2ed364ff196b755e91b77bd'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197301-197312.nc' 'SHA256' '3e7ad8a5ddabafbaa23ed77323accf210a67cc6a93918088bedf9257942b36a5'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197401-197412.nc' 'SHA256' '4c2efc320e2c8208a09786ebd5e5d4a385771db6fab24ed01b6a1ae6c12d5aeb'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197501-197512.nc' 'SHA256' '5deaba06d5f1ebff07ec11f6a08a1f268176bb4b740257b3660405b6a4a73424'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197601-197612.nc' 'SHA256' '18ae1c35d49c0876f4bb3bc57d67a5b2d484effbabcdf22741d3632555d3cd08'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197701-197712.nc' 'SHA256' '54292dc27d9140afd22692d1fbe445d4ad3024d3389094dbcdca84900e6a652e'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197801-197812.nc' 'SHA256' '6f5c55097ef97c19a88be14f7a416040ebf925a9b0c983e54267d04736843c89'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_197901-197912.nc' 'SHA256' 'd4be667e4cfcca1f292c6c160d2f7802c8972501098487260b7cf0c8fd2b1e9a'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198001-198012.nc' 'SHA256' 'de7fea7a685693658f32b36e8044d588f63bbe5a085fdab0dd57d8668d1e5aa2'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198101-198112.nc' 'SHA256' 'a25357a20d0ed4d8161462e98f16ff608b62a7613c23e99f28d4d7d37567be22'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198201-198212.nc' 'SHA256' 'b9a3a501c03a3d970a30b5646c6c6583427cf5d6be40f50d66567fb89b5ca4cc'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198301-198312.nc' 'SHA256' 'b3b9e7b51f8b67a18a669920e56ac898d40a60dfe6692697c9c87ff596319f54'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198401-198412.nc' 'SHA256' '7020fba7b394819398f5aec6115162d0c8db9235c547e6c94d783873a7eccc54'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198501-198512.nc' 'SHA256' 'ab3d8409b0f00c45debcd85bb271e16d53734381913e75114e5207d2ac50c497'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198601-198612.nc' 'SHA256' 'e29339a1eb52479003b940ea8fd777424038f3cd421c7072d0a21a0c37cfc259'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198701-198712.nc' 'SHA256' 'e7c764aa55586cb28ac66491b800b9adf45d1c46d9554e60c3f66f2d98eb9fbf'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198801-198812.nc' 'SHA256' '8e0a390f7ea5e22d4968783c8f7cdbd32b21fdabc882be2a11fb3145fad1dbda'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_198901-198912.nc' 'SHA256' '74d91db535b363c7fa6537cd618e686594ea8207e6801186cafac3db24bb8580'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199001-199012.nc' 'SHA256' '3f0c840581035208451d782527bc4294d18fcf443b4f440f5db50865c0280605'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199101-199112.nc' 'SHA256' '3a9191acece8dce48bbc4c08ba72f4a3d9dd28502b9a14d16946b7286f93b2d5'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199201-199212.nc' 'SHA256' '9ebe395a16130bcffa17db4d22c43c3f170f97e0fceac2cc9de639b6ab6d1c5f'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199301-199312.nc' 'SHA256' '39a1e0fc1a67535198ee61df05d01e6c227ba6276510b6ead15964c22e2125cc'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199401-199412.nc' 'SHA256' '2a4d0ac64f71f37826dde40b34b0c4464acc85a903caf6bfd5b68f877b251ea7'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199501-199512.nc' 'SHA256' '3c6e957b98b6f53bde3a60b9f1db1178eb60d6d386fe2b344bf667e71c2bfbcb'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199601-199612.nc' 'SHA256' '533b3032af9870bf2c8ecf4f04a5017d792434178dc82fdbd2783be2d454a1f2'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199701-199712.nc' 'SHA256' 'a061d70385c76cc8cc3701b11380fd6a7f5124bf56cf9c349d4f5011d76490aa'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199801-199812.nc' 'SHA256' 'a2a19b32d5e10c43435ceb938ad647df42d4ee74951953e799040b7a59913b8e'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_199901-199912.nc' 'SHA256' '31b6375285701c19c0e11395aeab635bb5ed9f8d3673bd840a76d3c7936c6f48'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200001-200012.nc' 'SHA256' '42b868b85dd5c7004f05881f780a0e19ce116d8636d6ca8e23260269422df015'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200101-200112.nc' 'SHA256' '1e2371bae9593c556a72a91efa74e675867b84b4b28c8fb3d93089089cb790d2'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200201-200212.nc' 'SHA256' 'e86104fb4d5dde88ade78f390feeb94d907c6b60790562f80218516883efbd6e'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200301-200312.nc' 'SHA256' 'ef1a698acfe80ac190d264aa5d4f69dad03fdf92fe76af09be1a92cf2599fd14'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200401-200412.nc' 'SHA256' 'b4c5581d4e08b5d11c1b255b6f2157a0c7cabd77d7ed47679fa0ddccd52dfe12'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200501-200512.nc' 'SHA256' 'df75301d310191091ef2840646d79818bb6e2e7ea117738b1b518c793a5ebdf7'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200601-200612.nc' 'SHA256' '261803c7601ca237fcd9fefb2b9496eb0e3255e6237dadd270cf8dfee01ae4a4'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200701-200712.nc' 'SHA256' '0a3195af8799f33a9c6f3a3dc1d758aec9818d2504cb4ae2c5c17d328f13623c'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200801-200812.nc' 'SHA256' 'f3e60f4260c1c51699ca1bfc23ea43b1a2372bb3adfeb6da684e4990f64d783f'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_200901-200912.nc' 'SHA256' 'baa84bb68a11d303855bf565f2d9c2682214d0b62c4cca9af4307fe7dcc513da'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201001-201012.nc' 'SHA256' '1364d22bbe618fda49cc142b2a84f3634ac8b48b1f31db9ffac0be4c5d16b4af'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201101-201112.nc' 'SHA256' '104a89a919c6a55492c1787d814f7738eef6a3f50a321b00682dc9a12ae921cf'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201201-201212.nc' 'SHA256' '24ce1379f48a7b1405713b2fb6e1785e312cc3fbb45564138ae70b1f1ab3559b'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201301-201312.nc' 'SHA256' 'ee4e521a8690345aea63a28efcbabcfab84bf9497b493ea84520d02755729486'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201401-201412.nc' 'SHA256' 'f77f7088fdcda4631d6e2e9d70b4d1e25fdfe06e72abb3eb5a77638fb26f75cb'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201501-201512.nc' 'SHA256' '41c52c4c9fa77c580af0f34db9e8fb95b901da3eb49a832fdb9dd0bd2e149009'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201601-201612.nc' 'SHA256' '18e918baed92f0f060f0a14d756def880635873b35c2b06b4aa6c2dbbc796040'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201701-201712.nc' 'SHA256' '514aa12003e304e4ed07c327d6abf3c5302bd2ec60a360e9a09f2e9072623adb'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201801-201812.nc' 'SHA256' '9fa0b34ac4162cfec03a3ca2e0634ac26dbba6d01b4fb2e02c98f335f9f79990'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_201901-201912.nc' 'SHA256' 'e8a6dece18109f528884e1d95320199c6e721188f0b93c9b72315d49fd05cfce'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202001-202012.nc' 'SHA256' '67b98b3e345ff2b1cb11238d3ccef591b5b91a3f83a6b15bb3bfc16a4965070d'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202101-202112.nc' 'SHA256' 'a8102d52d526967af70c766b99d0a85ec5aec5d4b99a32df9d52736706b4778a'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202201-202212.nc' 'SHA256' '6ddba97585442fcd8372bb5617ea744c7140641f50b649088bcce76b8829c429'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202301-202312.nc' 'SHA256' 'fdc7ab1fac985f5d9d0f3ced66523e33545fead8a506b1043adf723fe0c92ec3'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202401-202412.nc' 'SHA256' 'd0ce75f93a17ea80ae50a25a259bba12f1ae15491394e9589c9745f747b79b69'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202501-202512.nc' 'SHA256' '0a164363c171d771c9fa85200926334a8146382e8a735352f2c527a3d3d6be7b'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202601-202612.nc' 'SHA256' 'de48b68a3f8fd83f402a9c5d9f780671439325ece918afb8edbf2894be568444'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202701-202712.nc' 'SHA256' 'c9331aa39b6bcf56ad7d616cd119e566c633e98a74d07147d3dfffa7389505f0'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202801-202812.nc' 'SHA256' '445591b6d86d0880ec43178d61e15d21bf67b7735ab2ff56cf9b5c97d31fdb08'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_202901-202912.nc' 'SHA256' '714dbf843aa5a9aeb4dcce196b6881e87b9143fd087a27c7ff27fda7e1c4604c'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203001-203012.nc' 'SHA256' '7cb430db6f10dd7d4949948a8fddc833251b11451fb064c203d4c31cc9fedc95'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203101-203112.nc' 'SHA256' '2d39ac1dc189f7ab6440940c3847ce009321a84b7932e4c115e70d18aaaa034f'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203201-203212.nc' 'SHA256' 'e2552d1a111f6972bff63f1082ff269a10c6bb94d8e35e59d8cf29d29c8efb38'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203301-203312.nc' 'SHA256' '4d089692271d777e14cfa6b299ce95250cecfdb3f3ab02e4cc438bc340845429'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203401-203412.nc' 'SHA256' '74eebd70b90311b046ad0f287751602b7ab14cba26143841ffbc09ababfbfe35'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203501-203512.nc' 'SHA256' '785ee514e26418786350c578fad97f56eadbaf77129e32987d9cbc184a2a7064'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203601-203612.nc' 'SHA256' '3e9f102557cdc9cd07b7802ce76b7bf94db3986127e949fbbcb4053d17b4f933'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203701-203712.nc' 'SHA256' '62d547fd47e8e5bbe6af7312df2e5ca670c38698bb429436e09702fdd79efcfd'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203801-203812.nc' 'SHA256' '1f7040b4acda1142fe666565b4237a3c42041487a9161306d29efe1b45037ada'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_203901-203912.nc' 'SHA256' 'e3813f5be8a7870104eba8cfe2eecce6d243421c2008486e3d5c2f22e407068a'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204001-204012.nc' 'SHA256' '815d02a90a05a1ff4f891c204546818c6fb84daa6789660ed2b65eab9c554f35'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204101-204112.nc' 'SHA256' '84cb8f41cde1308542545597ad832dbf61b5e54e1206c67e8db9f120c545ec51'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204201-204212.nc' 'SHA256' '5623ac07bda919e560a35dc5b13255778be90ae2f8ffc2e1cee5c2953d65bb5f'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204301-204312.nc' 'SHA256' '06adaa14de48ae38f1ec3aac4a6471fdc154bf6917708f1c911f905b63a7cb6d'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204401-204412.nc' 'SHA256' '7d18c45d63479832cf0738ae7c8d343844f612860f81d7318db634231724289d'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204501-204512.nc' 'SHA256' '9c1f599b92308f8c2d8e9ade249d87b4b48ab15dafd764f97ec779573c43a1d9'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204601-204612.nc' 'SHA256' 'c0ef2ae10d4902e44774c267f70f0faa256c3b0ae8624ad7edb95406cbc0555e'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204701-204712.nc' 'SHA256' '79953111cd2fbd2ee603a46ce2d1bbdc24e88c717abcc2a0dd4ba53626ec5258'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204801-204812.nc' 'SHA256' '30ebbd069a75707b82c37d04a7962e41ecd07c55afedf832c038b3b9d84e0972'
'vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/control-1950/r1i1p2f1/Omon/vo/gn/v20190906/vo_Omon_EC-Earth3P_control-1950_r1i1p2f1_gn_204901-204912.nc' 'SHA256' 'd3ad864a1eec58f04d49d7aac029cc7039741268fd9ce06ab3f2592db51ff4b7'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 100 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
