#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-data.dkrz.de - 2026/01/09 09:24:41
# Search URL: https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.hist-1950.r1i1p2f1.Amon.rsus.gr.v20190314|esgf.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.hist-1950.r1i1p2f1.Amon.rsus.gr.v20190314|esgf.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195001-195012.nc' 'SHA256' 'd3644de0649a1cfff142aaf5b163a954f8c4fc50a01dac082171562c1965d7bd'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195101-195112.nc' 'SHA256' '95dcefa85e11665befdba81e4bbc43afe0f1b37cc316a6b7ba5e86a57284b871'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195201-195212.nc' 'SHA256' '6b94ba1dfd8dff45c27c12965f73df65aa9d63c054302467c05d3bf6f230f4ff'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195301-195312.nc' 'SHA256' '1a9b719b967c754abf7a872a96ba8ee5fe649c7da367dbd14c9442ec07c24b39'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195401-195412.nc' 'SHA256' 'db126169a02a36d595fc42e4dc50c56fbf58dc43ed440417ec0804ea1d664e31'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195501-195512.nc' 'SHA256' '3bde41a33ee6fa513ca373a84d73af28117b7264c857905ca0be34ac4e4d5360'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195601-195612.nc' 'SHA256' 'da469c5284be9e2e89484c2e95d45261f29c086b67388eb98590c75b3e1997eb'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195701-195712.nc' 'SHA256' '6ef45d5008220721d029a3e726309552c2f40a677ae22b9d6db3544d36210530'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195801-195812.nc' 'SHA256' 'e01028bdc135d5998244c7f8a359931c650907f73039188798cff41521e2015f'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_195901-195912.nc' 'SHA256' '130d0663ccbdf0bf01437691f79dbfbad7ffc70e1f25739d369ff70722d683e2'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196001-196012.nc' 'SHA256' '5217c7f14eb0e4ff2075efb3a7508bd63b2e11749fdd504f2004a33af1ff69d9'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196101-196112.nc' 'SHA256' '47cb5096865e0cdfe9cee768a64bf2eb46088073a985f5b38943cc03c85f1464'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196201-196212.nc' 'SHA256' '4ca1522193d728a34ef3d288b822bd78467f3b334a65d50921f1c5985d22e180'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196301-196312.nc' 'SHA256' '262d70c3d0e27a8976ecd32cff0308253019a3f34a5a85711f616fe81a0788ec'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196401-196412.nc' 'SHA256' '0a8e96df0eae73a1828e285c550e4fe6d2a06911b198174af599341848442ed0'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196501-196512.nc' 'SHA256' '119e7fa58b9e837494372fd4e88735e2708e255f19d1b3ce9bcfc3b1ea4e1b1e'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196601-196612.nc' 'SHA256' 'ff57a203d322d6c9e9e94fa4d95629e1640dfbf78eb5f0fe7e3c524c7bc2da3e'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196701-196712.nc' 'SHA256' '6f5f4ee2bc5708462605d2a2a136603ce044e1adcbca9bfe991b4e7269e38a73'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196801-196812.nc' 'SHA256' '4b7b3fd2b88a9cfed386ec5230543b42c1c4207085401d25fbf20254ccf40e58'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_196901-196912.nc' 'SHA256' 'f762b55ac3edd6c6f365dff573ba44ea0c9cbe11832ebc0b6301df4cd03d542d'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197001-197012.nc' 'SHA256' '7faae94b27990ef596ea935128036395c9b01a311369b1ca3d6570d2dfaa94a6'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197101-197112.nc' 'SHA256' 'cc48e92ee0b6c7858139bf407cbf6e8415bab712166233064ead930b35ab9d1b'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197201-197212.nc' 'SHA256' '37185988b037c12ea59e97cc44c27ec91e38cdfe6d0c8a67181143a841130e6f'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197301-197312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197301-197312.nc' 'SHA256' '119cafcba6bd34a1eef40949e343209cc210d6e66bd14b09aa57cf8648c08d5b'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197401-197412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197401-197412.nc' 'SHA256' '3b95019aa3579f28aa7b673e311355d76b58216a3fe1f71634c68e6d5c42412a'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197501-197512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197501-197512.nc' 'SHA256' '253364237213b372c09b4e22544debb4701a3ea77a71e65d574d1ba834fe67b1'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197601-197612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197601-197612.nc' 'SHA256' 'b10e21392239bf8e802f7f6b834cea3bf486293be3444cb9ee8c53a36bc961ff'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197701-197712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197701-197712.nc' 'SHA256' 'b96339b7f3a21b158e73f2c125161233a5dbbbc7394609e8a055b5c652773b37'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197801-197812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197801-197812.nc' 'SHA256' '302b1bf044d43e3bfe87328231ecbc54230100c4a8cf809d22638fc0dbecba78'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197901-197912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_197901-197912.nc' 'SHA256' '629a09449d7b97324918d5dc70cc97c80e27aaa860917142060c227cae5b3aa0'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198001-198012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198001-198012.nc' 'SHA256' 'c50f5ee33a5449eff9f680e25814622d5421906eaa30a27458d10356ea4c58bf'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198101-198112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198101-198112.nc' 'SHA256' 'f64e0742abf75ab9a4e11f40849ee88b26578f9970470a60c95cecfb64491a59'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198201-198212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198201-198212.nc' 'SHA256' 'e6acaf92d16fcb9ff8ca6c0e92f84f3cecb22d14e5988dd96d039a4ef6e4164d'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198301-198312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198301-198312.nc' 'SHA256' '00c0828b85a9decd6a9c0e25ce7d9a0c2513288853fe6afe0711c7ae05463e3d'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198401-198412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198401-198412.nc' 'SHA256' '9297373d94528ba3fbefa614050c466e781a86d631436bc04c17774f5dd2bf09'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198501-198512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198501-198512.nc' 'SHA256' '9c29e662d431b9efaa460fc2f9c7dbb77fd3b4f72ae8bc4d16f1609b4987ee86'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198601-198612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198601-198612.nc' 'SHA256' '458f287e2bbf467fdf4da068617f3a9104cd6d42c2e927c74a8d696e1962a92c'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198701-198712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198701-198712.nc' 'SHA256' '0c22e7466422fa56e76a47571872cca2d313bac888418065f0fbbe65a7014470'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198801-198812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198801-198812.nc' 'SHA256' '7528c78956609b8bca5cf70ddb1ca44cfeb29640f7289842a0da9efe8f3affe6'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198901-198912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_198901-198912.nc' 'SHA256' 'df41e0c4ad5b402bbf7a43784c94967751d4ee22ee3a1264ba4cd0313e42f7f6'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199001-199012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199001-199012.nc' 'SHA256' 'f2a2acf4cd5498c7de433b85f485bde0c69ee29e8060360861bffb94c7772ea2'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199101-199112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199101-199112.nc' 'SHA256' '1ab750d4dcaa61dadf65701ee6da49dfc5d1e83738bdd6e5aef028af4bc7b746'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199201-199212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199201-199212.nc' 'SHA256' '3b251acb53f70f072a858e3ddf827b8c9a43bc50a93236f8ab0fc8d17a5975e0'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199301-199312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199301-199312.nc' 'SHA256' '1c7b70457244a01640a9e725bc8da06c514733c572c5812b8e620ea273aa802e'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199401-199412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199401-199412.nc' 'SHA256' '5933b30ac7dad72e5df76ab0b5a7c645686f804f309a483d8430b582db592d31'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199501-199512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199501-199512.nc' 'SHA256' '94441d2454d3ee6dce0f8081851f13ed91862ff92033ea4947dd9f396c39a707'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199601-199612.nc' 'SHA256' '67b9ff033e463f490f94fddcd0f4abafd4bfb3cd646496ebd9b5bdcbac612943'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199701-199712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199701-199712.nc' 'SHA256' '694692e0f2c47b89fdaf293176e8ba638c4a3041af5ad2ba12471a64c599471d'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199801-199812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199801-199812.nc' 'SHA256' '7826d7e5edbc4e912fd0d63d7912afd34fcf2419f09563954e07a2632e51b999'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199901-199912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_199901-199912.nc' 'SHA256' '91205b1b06055904b67443a038cfda5688ed9b9ed872d881c1445cf8caa05984'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200001-200012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200001-200012.nc' 'SHA256' '3412846cf4782cb15263943709c69cbb0d5e770bf81b6d33dbde8deffc3d0b6c'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200101-200112.nc' 'SHA256' 'b2c717a45d145bf31b95e94f6e662daee3d844a9a1f1b773904e452c70b0fa74'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200201-200212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200201-200212.nc' 'SHA256' '926d16b7e2de8b796633e3e101f9d343c7045b74328ac59171a92fe51d48dd0f'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200301-200312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200301-200312.nc' 'SHA256' 'ebdc89f175c2c4ebbb7a52fbaf59be27160c17e9382d825d5268d5e52c55d31e'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200401-200412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200401-200412.nc' 'SHA256' '8d38c1ce4b43224ffa8025e47533794a3fb678872c9989673a259e813ccffc61'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200501-200512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200501-200512.nc' 'SHA256' '27f67364727073ed2d6bd28bd6c5f46edb09af1604503418c78c4c41d1565c57'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200601-200612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200601-200612.nc' 'SHA256' 'fcafea524d0e518a976bdfa813e119540296893a37932d2dd70b99a11b55de9f'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200701-200712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200701-200712.nc' 'SHA256' '282473b646495c1d1cb4556658f276c7a5af46c230e66ad8e096ecd785a7d23d'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200801-200812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200801-200812.nc' 'SHA256' 'abe75e6ba431abffaa4b789cca564f923991de268635e5b54c00707c0aea1b5c'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200901-200912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_200901-200912.nc' 'SHA256' 'bfb93d2ff05dfd60c5461fbd8265308e3c670e7803d0b7a2025d584a4bd7fed0'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201001-201012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201001-201012.nc' 'SHA256' '0b5b8c1cbeb662433337d323139c200213cfae25d64305f079127bf50793448c'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201101-201112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201101-201112.nc' 'SHA256' '6ef90b6ff652c521758e88e94b36c1f72d5a6a350d880d5361f18cf01fc1369b'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201201-201212.nc' 'SHA256' '9ce2c0cda2764deaea3d90bd96bf2bb6df6f682a0f3a1162f6ea50db7494c45e'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201301-201312.nc' 'SHA256' 'd8100b49b5f247cf120578e1e2180eb2be8f17be578b270649fd6ec5d62461c5'
'rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/Amon/rsus/gr/v20190314/rsus_Amon_EC-Earth3P_hist-1950_r1i1p2f1_gr_201401-201412.nc' 'SHA256' '882293b11d74cab8b293a9dfaaf975e218c1a094234103677b313be47acd5d87'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
