#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-data.dkrz.de - 2026/01/09 09:24:54
# Search URL: https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.hist-1950.r1i1p2f1.SImon.sithick.gn.v20190314|esgf.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-data.dkrz.de/esg-search/wget?dataset_id=CMIP6.HighResMIP.EC-Earth-Consortium.EC-Earth3P.hist-1950.r1i1p2f1.SImon.sithick.gn.v20190314|esgf.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195001-195012.nc' 'SHA256' 'af0bde4451034020fde458470f1b5bb4e9c2219d0fd138559b8d51cf03ff566d'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195101-195112.nc' 'SHA256' '25272d8c7f53454c5f367feb8fbbf288983fbb05301d71c6e190499781b6812f'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195201-195212.nc' 'SHA256' 'f86777a5304194495f1965dea3a76d641997b2aa8f0268c72f144cada53fcd30'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195301-195312.nc' 'SHA256' '5b7884a03ecd0aec82a50edd12d930259ab58129e7f384478b17b2df11a0655d'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195401-195412.nc' 'SHA256' 'e59ccd24b464943426f7e931420148c80790dbdae2d37a72e1b3af0943bc4291'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195501-195512.nc' 'SHA256' '59ad7a4b26b8c2bb9d871667cc38d57bdfdff001212260fd2557a86d6832b153'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195601-195612.nc' 'SHA256' '1a0566f0ac2ef6030c5c2d62fea685cfe01e33569cb05bc4829c775108be2be1'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195701-195712.nc' 'SHA256' 'd36abc2691845bdc42e8884ff64faea3a76603e68ca2fe745ddd90b12049d6d5'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195801-195812.nc' 'SHA256' 'cbde7b60f7ca4a0222e3148d961847155495258b5184150fbf95ff267b1699cd'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_195901-195912.nc' 'SHA256' '793077b37ed6bdbfb0d7e4b84151963e210ee596c2786524d224c2b5f660082f'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196001-196012.nc' 'SHA256' 'd53e9ec25fd5993c99c677ec2df8833f212c0c7915a4e18d58f5db722858a5f2'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196101-196112.nc' 'SHA256' 'ac4b7e86f8b2db08da6a673395e48377b4c01dea1d09859d2d818f9716e5a708'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196201-196212.nc' 'SHA256' '0a1fdca3100c5458ecba830c4ce787bfc00fd57498cc27f21fcfb17aec695fb6'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196301-196312.nc' 'SHA256' '9132ce012247238e7346f8e365eb1d4f831ab63c200f7dd5eb79c390d3baeb16'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196401-196412.nc' 'SHA256' '7a3244c2c945322342e5d8ae90d6ed85d0081e74c96997954d4bc7ad13c0e29b'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196501-196512.nc' 'SHA256' '7d4bd6519ba142ee575e5ab469a1dc7fa01573f5968ce358dba2ee943fc60dd7'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196601-196612.nc' 'SHA256' 'e10d1cd7e922f2b2b5853c09d8a581f13c9ec3e4bd5dd35e9f381b56e6d9c15b'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196701-196712.nc' 'SHA256' '9186ee310ba12408e2f17d4d2338df51d3dd3783ea9dc6b1cd9938514ca44ab4'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196801-196812.nc' 'SHA256' '616a2dc08abff8355703efd5fa3ed5435f59d5cf5ed80b0cd1f280e17138044f'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_196901-196912.nc' 'SHA256' '727518f624f1c580ed24630e5e86820700af24003d0ade1f91951aef0f036289'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197001-197012.nc' 'SHA256' '7b196bd6ef8fd3e88e97d82646f18fcf19e98e11e7d952216abc41a81ff381e1'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197101-197112.nc' 'SHA256' 'eebf6b2490d44becacc9f72d2c2ba0a04a663fb7725038112af598b27bea72f8'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197201-197212.nc' 'SHA256' 'c076aade81bd7607115999c5e908c4a2c778adbe6f28c68d07a0c7de6cf9adfe'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197301-197312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197301-197312.nc' 'SHA256' 'de24281fb3707e9fbc463b752f2d263472f8bf147ab4f3846fff998217ade479'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197401-197412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197401-197412.nc' 'SHA256' 'b8e9e7d59c84428d870f6bca574fc18a34675af30ec9bc957495d79f7cd7c271'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197501-197512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197501-197512.nc' 'SHA256' 'eb9d19c9457649008558e1e85ecb28472bd77351210621d372f2d3b97d6f6277'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197601-197612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197601-197612.nc' 'SHA256' '4d239882ccbb9185213b71664c026792708b7cdd9082e70d1084408b644920fb'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197701-197712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197701-197712.nc' 'SHA256' 'd75c2411c4a7f6092e33e4db22f4c08fbf83af082b92a7f0c3b7f0a93d4a8708'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197801-197812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197801-197812.nc' 'SHA256' '9626523fcb0b592d0cbda9cc18cb6cae739486278d9caf39d32ff07a5396628f'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197901-197912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_197901-197912.nc' 'SHA256' '63aaf8d8438de8b5e0db2b0e1cfcc4edba02e77cb789881d05670c9881d05546'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198001-198012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198001-198012.nc' 'SHA256' 'b07c922c387c8080c982567a5306b646072a4f1d02f0f5b6465318143ada1ffc'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198101-198112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198101-198112.nc' 'SHA256' '0816ceb97dd0b476a331992a783f7828c6b96ad4fd3a09990252562947b487d5'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198201-198212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198201-198212.nc' 'SHA256' '70278966a5fb074785e43f1a8ab32b07408bd60c89be1a12975cfa5e1d799cad'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198301-198312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198301-198312.nc' 'SHA256' 'ad9287e1ee1d6b1ad128242888e0bcf7519cbeb27c580419a4557071d83239cd'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198401-198412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198401-198412.nc' 'SHA256' '5a83b4dac05360cc8725eed5416f6b78198dd4a1cedf32c04b23e60511a71836'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198501-198512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198501-198512.nc' 'SHA256' '1b69c117ef4c6dbdea4ff47592b100ab8312078686bb79779796aabfb72ab1bc'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198601-198612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198601-198612.nc' 'SHA256' '674d8c529672d17a3e6fcc268c66be6bfacba45cf868fea7a4a398fdd67a3d73'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198701-198712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198701-198712.nc' 'SHA256' 'c6153dd9cea3edd1d608e17d03e28c56340ac28098a728c6918d34927620a535'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198801-198812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198801-198812.nc' 'SHA256' 'e748db72da390288c6cfa1bca71fd8dad10bc90a851390ddbbd6836dc2a238d3'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198901-198912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_198901-198912.nc' 'SHA256' '3b500ee6e7c0b3ebc7c9da0943c1855f0e385650ae4af57557d7fed4007ebdee'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199001-199012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199001-199012.nc' 'SHA256' '51f0a13ae8e2876d872ef8253ffb470faeccb91a41fba781d095702c11ee8559'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199101-199112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199101-199112.nc' 'SHA256' 'bdc1266b0ed5078f2460fdb49d765e807df76634f5f44d0dc5e177df426bc11b'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199201-199212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199201-199212.nc' 'SHA256' '91f7710435aeb6a594b3b78daf6b09ed8449100877abbc51c308d025b1cd79d4'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199301-199312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199301-199312.nc' 'SHA256' '3a04a799b230bc7a3304bf59fb7dcfbb8c7d8d8f5a51d1aa8fb6e92fdf347d7a'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199401-199412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199401-199412.nc' 'SHA256' '2cc4a14921fdf7ae9650893fce62e6eaf8309ff44269e2c9284bc4aa8ca5188d'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199501-199512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199501-199512.nc' 'SHA256' '8c9e4697d28da14bcb82df4b04047c5a273209493c2aedd764e34352330bcddb'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199601-199612.nc' 'SHA256' 'f865a04bfe4deb8c5cbf649e7df91f48d287807daf4996af0cc3eb2450013d36'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199701-199712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199701-199712.nc' 'SHA256' '6ff2a6ff4522fe2c494e6274a37782a46d9c1d6b6ec1107b8e1f58e97ece6f8e'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199801-199812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199801-199812.nc' 'SHA256' 'fba8757dd33e6433272380afacd8dde0d51edff9066777e77f048428f0fb8771'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199901-199912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_199901-199912.nc' 'SHA256' '956e57306765e49cbd02bc53257183c73df9a252b08a20f7dbae33fba966088a'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200001-200012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200001-200012.nc' 'SHA256' 'e19e19cf632fc35b696dc30ffe893ae26d4bd20d9c9665044c464865e93a7a17'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200101-200112.nc' 'SHA256' '1bda1afca2f41f9c7d4ff2f46f373bc5dc367effdd0534d17a40ce009223717b'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200201-200212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200201-200212.nc' 'SHA256' 'f616217b219d3957c3a56d897c014f5cefae3c8615065a7ccb25cb5938c1f7f9'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200301-200312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200301-200312.nc' 'SHA256' 'f8ba0efa86d1d34d4438411f987c71a0f7047e8928d91a41c86431ba835f4c15'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200401-200412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200401-200412.nc' 'SHA256' '3b31a0423a56e9dadc1dddf008ddef8ef99808e634a4f31b45bcf402c31e3afa'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200501-200512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200501-200512.nc' 'SHA256' '500f0974cadcf47dee4073b7611400a2576975175d970dd06b27569032014dae'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200601-200612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200601-200612.nc' 'SHA256' '861b275d875a5c68f5581ae33aff336571c694ca670925bcc37b2932a0d2db0d'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200701-200712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200701-200712.nc' 'SHA256' '84d00dc5f7376f7d51fd09e9f42816afe8ae488ad5b5dab4559265b2d99f56dc'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200801-200812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200801-200812.nc' 'SHA256' '1c2627efe5fdca6fcd2093441d84ca44f8c7c779287bc41789ca4509e888e998'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200901-200912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_200901-200912.nc' 'SHA256' 'd8adbbf891d959d8b204d71b909a725fe344a54d86fcf760fe8d9a65f2f7132b'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201001-201012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201001-201012.nc' 'SHA256' '0730a5d7f0f4bbcdd6de409aa47fc8c45d472388f1caf983fba442dea1ada7fd'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201101-201112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201101-201112.nc' 'SHA256' '6aafa4d07702e91ced2be103bb29fe530a3c050be149e7d16521f80288f27c31'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201201-201212.nc' 'SHA256' '83fa2db76eca13496564ea8bf69148b682d2d2b95d7136dad969558f7d8a6fd4'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201301-201312.nc' 'SHA256' '58ace3ead8c0640d3a981204e51788b134107315c1cc4fa7663227a2b87a80f5'
'sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/HighResMIP/EC-Earth-Consortium/EC-Earth3P/hist-1950/r1i1p2f1/SImon/sithick/gn/v20190314/sithick_SImon_EC-Earth3P_hist-1950_r1i1p2f1_gn_201401-201412.nc' 'SHA256' '51e43d7330826e977c96b3ee68756956890dca969eca28d6bcb936ce396e1371'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 65 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
