start_year: 1951
end_year: 2021
start_month: 1
end_month: 1
nemo_version: 3.6
atmosphere_source: ace2
frequency: monthly
atmosphere_model_dir: /home/ecme4254/hpcperm/ml_model_data/ace2
config_file: /perm/ecme4254/repos/ace/configs/coupled_inference_config.yaml
atmosphere_repo_dir: /perm/ecme4254/repos/ace
era5_dir: /scratch/ecme4254/era5
ece_script_dir: /perm/ecme4254/repos/ecearth4/scripts
coupling_timestep_secs: 21600
forcing_data_dir: /home/ecme4254/scratch/ace2_forcing_data/control_1951-2051
from_restart: true